apiVersion: eksctl.io/v1alpha5
availabilityZones:
- ap-southeast-1a
- ap-southeast-1b
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
fargateProfiles:
- name: fp-default
  selectors:
  - namespace: default
  - namespace: kube-system
  status: ""
- name: fp-acs
  selectors:
  - namespace: alfresco
  status: ""  
iam:
  vpcResourceControllerPolicy: true
  withOIDC: false
kind: ClusterConfig
kubernetesNetworkConfig:
  ipFamily: IPv4
metadata:
  name: <ReplaceWith_CLUSTER_NAME>
  region: ap-southeast-1
  version: "1.23"
privateCluster:
  enabled: false
  skipEndpointCreation: false
vpc:
  autoAllocateIPv6: false
  cidr: 192.168.0.0/16
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: Single
